version: '3'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
      - smtp_relay
      - barong
      - slanger
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: api.wb.local'
      traefik.port: 8000

  barong:
    build:
      context: ../app/barong
    depends_on:
      - proxy
      - db
      - vault
    env_file:
      - ../config/barong.env
    expose:
      - "8001"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: auth.wb.local'
      traefik.port: 8001

  trading_ui:
    build:
      context: ../app/trading-ui
    depends_on:
      - proxy
      - peatio
    env_file:
      - ../config/trading-ui.env
    expose:
      - "8002"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: api.wb.local; PathPrefix:/trading, /trading-ui-assets'
      traefik.port: 8002