- id:                   usd
  symbol:               '$'
  type:                 fiat
  precision:            2
  base_factor:          1
  quick_withdraw_limit: 1000

- id:                   eur
  symbol:               '€'
  type:                 fiat
  precision:            2
  base_factor:          1
  quick_withdraw_limit: 1000
